image: node:latest

stages:
  - install-dependencies
  - dependency-check
  - code-testing
  - acceptance-testing

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

install-dependencies:
  stage: install-dependencies
  script:
    - npm i

dependency-check:
  stage: dependency-check
  script:
    - npm run npm-check
linting:
  stage: code-testing
  script:
    - npm run linter

unit-testing:
  stage: code-testing
  script:
    - npm test

acceptance-testing:
  stage: acceptance-testing
  image: buildkite/puppeteer
  before_script:
    - chmod +x ./scripts/after_each_acceptance_tests
    - chmod +x ./scripts/before_each_acceptance_tests
    - chmod +x ./scripts/clean_acceptance_tests
    - chmod +x  ./scripts/start_acceptance_tests
  script:
    - npm run acceptance
#  only:
#   - master
