image: node:latest

stages:
  - code-testing
  - acceptance-testing

linting:
  stage: code-testing
  script:
    - npm install
    - npm run linter

unit-testing:
  stage: code-testing
  script:
    - npm install
    - npm test

acceptance-testing:
  stage: acceptance-testing
  image: buildkite/puppeteer
  before_script:
    - chmod +x ./scripts/after_each_acceptance_tests
    - chmod +x ./scripts/before_each_acceptance_tests
    - chmod +x ./scripts/clean_acceptance_tests
    - chmod +x  ./scripts/start_acceptance_tests
  script:
    - npm install
    - npm run acceptance
#  only:
#   - master
