version: '3.7'

services:
  server:
    image: exchange
    container_name: exchange_server
    build: .
    environment:
      NODE_ENV: production
      EXCHANGE_DB_USER_PORT: 5432
      EXCHANGE_DB_USER_HOST: db_user
      EXCHANGE_DB_ITEM_PORT: 5432
      EXCHANGE_DB_ITEM_HOST: db_item
    env_file:
      - .env
    depends_on:
      - db_user
      - db_item
    ports:
      - ${EXCHANGE_SERVER_PORT}:${EXCHANGE_SERVER_PORT}
    volumes:
      - server_image_data:/usr/src/app/data
    networks:
    - exchange
  
  db_user:
    image: postgres
    container_name: exchange_db_user
    environment:
      POSTGRES_DB: ${EXCHANGE_DB_USER_DATABASE}
      POSTGRES_USER: ${EXCHANGE_DB_USER_USERNAME} 
      POSTGRES_PASSWORD: ${EXCHANGE_DB_USER_PASSWORD}
    volumes:
     - db_user_data:/var/lib/postgresql/data
    networks: 
      - exchange
  
  db_item:
    image: postgres
    container_name: exchange_db_item
    environment:
      POSTGRES_DB: ${EXCHANGE_DB_ITEM_DATABASE}
      POSTGRES_USER: ${EXCHANGE_DB_ITEM_USERNAME} 
      POSTGRES_PASSWORD: ${EXCHANGE_DB_ITEM_PASSWORD}
    volumes:
     - db_item_data:/var/lib/postgresql/data
    networks: 
      - exchange

volumes:
  server_image_data:
  db_user_data:
  db_item_data:

networks:
  exchange: