version: '3.7'

services:
  server:
    image: exchange
    build: .
    environment:
      NODE_ENV: production
      USER_DB_HOST: db_user
      ITEM_DB_HOST: db_item
    env_file:
      - .env
    depends_on:
      - db_user
      - db_item
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - imageData:/usr/src/app/data
  
  db_user:
    image: postgres
    environment:
      POSTGRES_DB: ${USER_DB_DATABASE}
      POSTGRES_USER: ${USER_DB_USER} 
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_PORT: ${USER_DB_PORT}
    volumes:
     - userData:/var/lib/postgresql/data
  
  db_item:
    image: postgres
    environment:
      POSTGRES_DB: ${ITEM_DB_DATABASE}
      POSTGRES_USER: ${ITEM_DB_USER} 
      POSTGRES_PASSWORD: ${ITEM_DB_PASSWORD}
      POSTGRES_PORT: ${ITEM_DB_PORT}
    volumes:
     - itemData:/var/lib/postgresql/data

volumes:
  imageData:
  userData:
  itemData: