#!/bin/sh

export EXCHANGE_DB_USER_USERNAME=user
export EXCHANGE_DB_USER_PASSWORD=password
export EXCHANGE_DB_USER_DATABASE=exchange_acceptance_db_user
export EXCHANGE_DB_USER_PORT=9911

export EXCHANGE_DB_ITEM_USERNAME=user
export EXCHANGE_DB_ITEM_PASSWORD=password
export EXCHANGE_DB_ITEM_DATABASE=exchange_acceptance_db_item
export EXCHANGE_DB_ITEM_PORT=9922

export EXCHANGE_DB_WISHLIST_USERNAME=user
export EXCHANGE_DB_WISHLIST_PASSWORD=password
export EXCHANGE_DB_WISHLIST_DATABASE=exchange_acceptance_db_wishlist
export EXCHANGE_DB_WISHLIST_PORT=9933

export EXCHANGE_DB_OFFER_USERNAME=user
export EXCHANGE_DB_OFFER_PASSWORD=password
export EXCHANGE_DB_OFFER_DATABASE=exchange_acceptance_db_offer
export EXCHANGE_DB_OFFER_PORT=9944

export EXCHANGE_DB_SUGGESTION_USERNAME=user
export EXCHANGE_DB_SUGGESTION_PASSWORD=password
export EXCHANGE_DB_SUGGESTION_DATABASE=exchange_acceptance_db_suggestion
export EXCHANGE_DB_SUGGESTION_PORT=9955

export EXCHANGE_GMAIL_USERNAME=exchange.acceptance.mail@gmail.com
export EXCHANGE_GMAIL_PASSWORD=Letmein123!

export EXCHANGE_SERVER_PORT=4040

echo '> Starting Node.js Server In Background'
node index.js&
echo '> Running Acceptance Tests'
node_modules/.bin/jest --runInBand --detectOpenHandles acceptance/*
echo '> Killing Node.js Server'
kill %1

