#!/bin/sh

export EXCHANGE_DB_USER_USERNAME=user
export EXCHANGE_DB_USER_PASSWORD=password
export EXCHANGE_DB_USER_DATABASE=exchange_dev_db_user
export EXCHANGE_DB_USER_PORT=9911

export EXCHANGE_DB_ITEM_USERNAME=user
export EXCHANGE_DB_ITEM_PASSWORD=password
export EXCHANGE_DB_ITEM_DATABASE=exchange_dev_db_item
export EXCHANGE_DB_ITEM_PORT=9922

echo '$EXCHANGE_DB_USER_USERNAME'
trap remove_dev_db INT

function remove_dev_db() {
	echo ``
	echo '> Removing Database exchange_dev_db_user'
	docker stop exchange_dev_db_user
	docker rm exchange_dev_db_user

	echo '> Removing Database exchange_dev_db_item'
	docker stop exchange_dev_db_item
	docker rm exchange_dev_db_item
	exit
}

echo '> Creating Database volume exchange_dev_db_user'
docker volume create exchange_dev_db_user_data
echo '> Creating Database volume exchange_dev_db_item'
docker volume create exchange_dev_db_item_data

echo '> Starting Database exchange_dev_db_user'
docker run --name exchange_dev_db_user -p 9911:5432 -v exchange_dev_db_user_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_user -d postgres
echo '> Starting Database exchange_dev_db_item'
docker run --name exchange_dev_db_item -p 9922:5432 -v exchange_dev_db_item_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_item -d postgres

echo '> Starting Node.js Server'
node index.js