#!/bin/sh

export EXCHANGE_DB_USER_USERNAME=user
export EXCHANGE_DB_USER_PASSWORD=password
export EXCHANGE_DB_USER_DATABASE=exchange_dev_db_user
export EXCHANGE_DB_USER_PORT=9911

export EXCHANGE_DB_ITEM_USERNAME=user
export EXCHANGE_DB_ITEM_PASSWORD=password
export EXCHANGE_DB_ITEM_DATABASE=exchange_dev_db_item
export EXCHANGE_DB_ITEM_PORT=9922

export EXCHANGE_DB_WISHLIST_USERNAME=user
export EXCHANGE_DB_WISHLIST_PASSWORD=password
export EXCHANGE_DB_WISHLIST_DATABASE=exchange_dev_db_wishlist
export EXCHANGE_DB_WISHLIST_PORT=9933

export EXCHANGE_DB_OFFER_USERNAME=user
export EXCHANGE_DB_OFFER_PASSWORD=password
export EXCHANGE_DB_OFFER_DATABASE=exchange_dev_db_offer
export EXCHANGE_DB_OFFER_PORT=9944

export EXCHANGE_DB_SUGGESTION_USERNAME=user
export EXCHANGE_DB_SUGGESTION_PASSWORD=password
export EXCHANGE_DB_SUGGESTION_DATABASE=exchange_dev_db_suggestion
export EXCHANGE_DB_SUGGESTION_PORT=9955

export EXCHANGE_GMAIL_USERNAME=exchange.dev.mail@gmail.com
export EXCHANGE_GMAIL_PASSWORD=Letmein123!

export NODE_ENV=development

trap remove_dev_db INT

function remove_dev_db() {
	echo ``
	echo '> Removing Database exchange_dev_db_user'
	docker stop exchange_dev_db_user
	docker rm exchange_dev_db_user

	echo '> Removing Database exchange_dev_db_item'
	docker stop exchange_dev_db_item
	docker rm exchange_dev_db_item

	echo '> Removing Database exchange_dev_db_wishlist'
	docker stop exchange_dev_db_wishlist
	docker rm exchange_dev_db_wishlist

	echo '> Removing Database exchange_dev_db_offer'
	docker stop exchange_dev_db_offer
	docker rm exchange_dev_db_offer

	echo '> Removing Database exchange_dev_db_suggestion'
	docker stop exchange_dev_db_suggestion
	docker rm exchange_dev_db_suggestion
	exit
}

echo '> Creating Database volume exchange_dev_db_user_data'
docker volume create exchange_dev_db_user_data
echo '> Creating Database volume exchange_dev_db_item_data'
docker volume create exchange_dev_db_item_data
echo '> Creating Database volume exchange_dev_db_wishlist_data'
docker volume create exchange_dev_db_wishlist_data
echo '> Creating Database volume exchange_dev_db_offer_data'
docker volume create exchange_dev_db_offer_data
echo '> Creating Database volume exchange_dev_db_suggestion_data'
docker volume create exchange_dev_db_suggestion_data

echo '> Starting Database exchange_dev_db_user'
docker run --name exchange_dev_db_user -p 9911:5432 -v exchange_dev_db_user_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_user -d postgres
echo '> Starting Database exchange_dev_db_item'
docker run --name exchange_dev_db_item -p 9922:5432 -v exchange_dev_db_item_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_item -d postgres
echo '> Starting Database exchange_dev_db_wishlist'
docker run --name exchange_dev_db_wishlist -p 9933:5432 -v exchange_dev_db_wishlist_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_wishlist -d postgres
echo '> Starting Database exchange_dev_db_offer'
docker run --name exchange_dev_db_offer -p 9944:5432 -v exchange_dev_db_offer_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_offer -d postgres
echo '> Starting Database exchange_dev_db_suggestionr'
docker run --name exchange_dev_db_suggestion -p 9955:5432 -v exchange_dev_db_suggestion_data:/var/lib/postgresql/data -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=exchange_dev_db_suggestion -d postgres

echo '> Starting Node.js Server'
nodemon index.js